stages:
  - build
  - deploy

# Build job
build-code-job:
  stage: build
  image: node:18-buster
  tags:
    - docker
  script:
    - npm install
    - npm run build

# Deploy job: Merge feature branch into main and push to GitHub
deploy-code-job:
  stage: deploy
  image: node:18-buster
  tags:
    - docker
  variables:
    GITHUB_URL: "git@github.com:MTech-cmd/bitlab-cicd.git"
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval `ssh-agent -s`
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$PRIVATE_SSH_KEY" > ~/.ssh/id_rsa
    # See content id_rsa
    - cat ~/.ssh/id_rsa
    - ls ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - ssh-add
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts


  script:
    # Ensure all branches are fetched before merging
    - git fetch origin
    # Check out the main branch
    - git checkout main
    # checking branches
    - git branch -a
    # check ssh connection to github
    - ssh -T git@github.com
    # Merge the feature branch into the main branch
    - git merge origin/feature  # Replace 'feature' with your actual branch name
    # Push the updated main branch to GitHub
    - git push "$GITHUB_URL" main
