stages:
  - build
  - deploy

# Build job
build-code-job:
  stage: build
  image: node:18-buster
  tags:
    - docker
  script:
    - npm install
    - npm run build

# Deploy job: Merge feature branch into main and push to GitHub
deploy-code-job:
  stage: deploy
  image: node:18-buster
  tags:
    - docker
  variables:
    # Add the link to your GitHub repository here
    GITHUB_URL: "git@github.com:MTech-cmd/bitlab-cicd.git"
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval `ssh-agent -s`
    # Decode and add the SSH key from base64 to ssh-agent (for ed25519)
    - echo "$PRIVATE_SSH_KEY_B64" | base64 -d | ssh-add -
    - mkdir -p ~/.ssh
    # Add GitHub and GitLab to known hosts using ed25519
    - ssh-keyscan -t ed25519 gitlab.com >> ~/.ssh/known_hosts
    - ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts

  script:
    # Ensure all branches are fetched before merging
    - git fetch origin
    # Check out the main branch
    - git checkout main
    # Merge the feature branch into the main branch
    - git merge origin/feature  # Replace 'feature' with your actual branch name
    # Push the updated main branch to GitHub
    - git push "$GITHUB_URL" main
