stages:
  - build
  - deploy

# Build job
build-code-job:
  stage: build
  image: node:18-buster
  tags:
    - docker
  script:
    - npm install
    - npm run build

# Deploy job: Merge feature branch into main and push to GitHub
deploy-code-job:
  stage: deploy
  image: node:18-buster
  tags:
    - docker
  variables:
    GITHUB_URL: "git@github.com:MTech-cmd/bitlab-cicd.git"
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval `ssh-agent -s`
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Add SSH private key securely
    - echo "$PRIVATE_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    # Configure Git user
    - git config --global user.email "ci-runner@example.com"
    - git config --global user.name "CI Runner"

  script:
    # Ensure all branches are fetched from GitLab (origin)
    - git fetch origin
    # Checkout the main branch from GitLab
    - git checkout main
    # Merge feature branch from GitLab into main
    - git merge origin/feature
    - git push
    # Push the updated main branch to GitHub (set remote 'github')
    # - git pull github main
    # - git push github main
    # First time push
    # - git remote add github git@github.com:MTech-cmd/bitlab-cicd.git
    - git branch -M main
    - git pull github main
    - git push github main