stages:
  - build
  - deploy

# Build job
build-code-job:
  stage: build
  image: node:18-buster
  tags:
    - docker
  script:
    - npm install
    - npm run build

# Deploy job: Merge feature branch into main and push to GitHub
deploy-code-job:
  stage: deploy
  image: node:18-buster
  tags:
    - docker
  variables:
    GITHUB_URL: "git@github.com:MTech-cmd/bitlab-cicd.git"
  # before_script:
  #   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  #   - eval `ssh-agent -s`
  #   # Create the .ssh directory
  #   - mkdir -p /root/.ssh
  #   # Write the SSH key to a file
  #   - echo "$PRIVATE_SSH_KEY" | sed 's/\\n/\n/g' > /root/.ssh/id_ed25519
  #   - chmod 600 /root/.ssh/id_ed25519
  #   - ssh-add /root/.ssh/id_ed25519
  #   - mkdir -p ~/.ssh
  #   - ssh-keyscan -t ed25519 gitlab.com >> ~/.ssh/known_hosts
  #   - ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts

  script:
    # Ensure all branches are fetched before merging
    - git fetch origin
    # Check out the main branch
    - git checkout main
    # Merge the feature branch into the main branch
    - git merge origin/feature  # Replace 'feature' with your actual branch name
    - git push
    # Push the updated main branch to GitHub
    # - git push "$GITHUB_URL" main
